# Generated by Django 5.0.3 on 2025-03-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_candidateprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
