# Generated by Django 5.0.3 on 2025-03-12 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_candidateprofile_github_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedrepository',
            name='last_analyzed',
        ),
        migrations.AddField(
            model_name='linkedrepository',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkedrepository',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='linkedrepository',
            name='analysis_results',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='linkedrepository',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
